name: dm-poc-cluster-mgmnt-pipeline
on:
  push:
    branches:
      - master
    pull_request:
      branches: [ master ]
    workflow_dispatch:      

env:
  PROJECT_ID: dm-poc-development
  # PROJECT_NUMBER: PROJECT_NUMBER

  CLUSTER: dm-poc-dev
  CLUSTER_ZONE: europe-west1
  REPOSITORY_REGION: europe-west1

jobs:
  cluster-management-components:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3


    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '>= 416.0.0'      

    - name: Set up Google Cloud Authentications 
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/635793351475/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc-provider-id'
        service_account: infra-sa@dm-poc-development.iam.gserviceaccount.com
        create_credentials_file: true
        activate_credentials_file: true

    - name: DeployCertmanager
      working-directory: cluster-certmanager
      run: | 
        gcloud components install gke-gcloud-auth-plugin
        gcloud container clusters get-credentials dm-poc-dev --region=europe-west1
        kubectl apply -f . 

    - name: DeployArgoCD
      working-directory: cluster-cicd
      run: | 
        gcloud components install gke-gcloud-auth-plugin
        gcloud container clusters get-credentials dm-poc-dev --region=europe-west1
        kubectl apply -f .         

    - name: DeployIngressControler
      working-directory: cluster-nginx-controller
      run: | 
        gcloud components install gke-gcloud-auth-plugin
        gcloud container clusters get-credentials dm-poc-dev --region=europe-west1
        kubectl apply -f .     